# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108550e4786a5047b9d00f552fe3ac0b0bdc3b07a1cf25d5368b3958d0c17c193b5461bc895c44eabd382297ec520bcda92e3e943800627628eb6128b6bb867f

test:
  secret_key_base: 991425cdf2115bd088be6e97b40f863e064219f326a1183aae9b7b32936a8b1a39e4dd41353b710c961dbdf9e9a1a5fd3bddc055e777e8b5e4197c00572549f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
